spring:
  application:
    name: skymates-content-service
  datasource:
    url: jdbc:mysql://localhost:3306/skymates_content?serverTimezone=UTC
    username: root
    password: 778899
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/