spring:
  application:
    name: skymates-gateway
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: lb://skymates-user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: content-service-route
          uri: lb://skymates-content-service
          predicates:
            - Path=/content/**
          filters:
            - StripPrefix=1
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/