#spring:
#  application:
#    name: skymates-eureka-server
#server:
#  port: 8761
#eureka:
#  client:
#    register-with-eureka: false  # Eureka Server 不注册自己
#    fetch-registry: false        # 不从 Eureka 获取注册信息
#  server:
#    enable-self-preservation: false  # 开发环境关闭自我保护模式